packages:
  - packages/*
  - e2e/vite-*
  - e2e/playground/*
  - examples/*

catalog:
  '@kazupon/vp-config': ^0.5.1
  '@kazupon/jts-utils': ^0.17.0
  '@playwright/test': 1.57.0
  '@types/node': ^25.5.0
  '@vitest/browser-playwright': 4.1.11
  bumpp: ^12.1.1
  es-module-lexer: ^1.7.0
  gh-changelogen: ^2.0.2
  semver: ^7.8.5
  tar: ^7.5.22
  typescript: 7.0.2
  esbuild: 0.27.3
  get-port-please: ^3.2.0
  magic-string: ^0.30.21
  oxlint: 1.79.0
  '@oxlint/plugins': 1.79.0
  publint: ^0.3.18
  rolldown: 1.2.5
  '@rolldown/browser': 1.2.5
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
  vitepress: ^2.0.0-alpha.17
  vitepress-api-references: ^0.2.1
  pathe: ^2.0.3
  '@oxc-project/types': 0.146.0
  obug: ^2.1.1
  buffer: ^6.0.3
  readable-stream: ^4.7.0
  wrangler: ^4.77.0 # for cloudflare pages deploying on github actions
  vue: ^3.5.31
  react: ^19.2.4
  react-dom: ^19.2.4
  svelte: ^5.55.0
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@vitejs/plugin-react': 5.1.4
  '@vitejs/plugin-vue': ^6.0.5
  '@vitejs/devtools': 0.5.2

overrides:
  '@napi-rs/wasm-runtime': 1.2.3
  crossws: 0.4.12
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    typescript: '6'
    vite: '*'
    vitest: '*'

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@kazupon/jts-utils'
  - '@kazupon/vp-config@0.5.1'
  - '@vitejs/devtools'
  - '@vitejs/devtools-kit'
  - '@vitejs/devtools-rolldown'
  - '@vitejs/devtools-rpc'
  - 'gh-changelogen@2.0.2'
  - knip
  - oxlint
  - vite

verifyDepsBeforeRun: false

allowBuilds:
  '@parcel/watcher': true
  '@rolldown/browser': true
  core-js: true
  deno: true
  esbuild: true
  less: false
  sharp: true
  wasm-pack: true
  workerd: true

patchedDependencies:
  fdir@6.5.0: patches/fdir@6.5.0.patch
