packages:
  - packages/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@kazupon/prettier-config"
  - "@kazupon/eslint-config"
  - eslint-plugin-oxlint

onlyBuiltDependencies:
  - "@rolldown/browser"
  - esbuild
