packages:
  - packages/*

catalog:
  '@types/node': ^25.0.9
  publint: ^0.3.16
  tsdown: 0.18.4
  typedoc: ^0.28.16
  typedoc-plugin-markdown: ^4.9.0
  '@playwright/test': 1.57.0
  get-port-please: ^3.2.0
  vite: 8.0.0-beta.4
  rolldown: ^1.0.0-beta.60
  magic-string: ^0.30.21

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@kazupon/prettier-config'
  - '@kazupon/eslint-config'
  - '@kazupon/jts-utils'
  - eslint-plugin-oxlint
  - knip

onlyBuiltDependencies:
  - '@rolldown/browser'
  - core-js
  - deno
  - esbuild
