/**
 * @vrowzer/rolldown
 *
 * Pre-bundled @rolldown/browser for easy browser usage.
 * All dependencies (including @napi-rs/wasm-runtime) are pre-resolved,
 * so you can use rolldown in the browser with a simple import.
 *
 * @example
 * ```ts
 * import { rolldown } from '@vrowzer/rolldown'
 * import { memfs } from '@vrowzer/rolldown/experimental'
 *
 * memfs.volume.fromJSON({ '/src/index.js': 'export const x = 1' })
 * const bundle = await rolldown({ input: '/src/index.js' })
 * const { output } = await bundle.generate({ format: 'esm' })
 * console.log(output[0].code)
 * ```
 *
 * @module default
 */

/**
 * @author kazuya kawaguchi (a.k.a. kazupon)
 * @license MIT
 */

// This file is for type-checking and IDE support only.
// The actual runtime code is generated by the build script (build.ts).
export { rolldown, VERSION } from '@rolldown/browser'
export type { RolldownBuild, RolldownOptions, RolldownOutput } from '@rolldown/browser'
