name: Deploy Vrowzer Playground
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout codes
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: false

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version: 24
          cache: true
          run-install: false

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Generate manifests (CJS to ESM bundles)
        run: |
          pnpm gen:manifest packages/play-vrowzer/package.json -p packages/play-vrowzer/fixtures/vite-vue -o packages/play-vrowzer/fixtures/vite-vue/vrowzer-manifest.json -t vue --name "Vrowzer + Vue"
          pnpm gen:manifest packages/play-vrowzer/package.json -p packages/play-vrowzer/fixtures/vite-react -o packages/play-vrowzer/fixtures/vite-react/vrowzer-manifest.json -t react -t react-dom --name "Vrowzer + React"
          pnpm gen:manifest packages/play-vrowzer/package.json -p packages/play-vrowzer/fixtures/vite-svelte -o packages/play-vrowzer/fixtures/vite-svelte/vrowzer-manifest.json -t svelte --name "Vrowzer + Svelte"

      - name: Build vite-dev-server
        run: vp run vite-dev-server#build

      - name: Build play-vrowzer
        run: vp run play-vrowzer#build

      - name: Create cloudflare pages project (if not exists)
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project create vrowzer-playground --production-branch=main

      - name: Deploy cloudflare pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy packages/play-vrowzer/dist --project-name=vrowzer-playground --commit-dirty=true
